{{- define "common.migration" -}}
{{- if .Values.migration.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-migration
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.migration.annotations | nindent 4 }}
spec:
  template:
    spec:
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      restartPolicy: {{ .Values.migration.restartPolicy }}
      containers:
      - name: migration
        image: {{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) | quote }}
        command: ["{{ .Values.migration.command }}"]
        args: {{ toYaml .Values.migration.args | nindent 10 }}
        envFrom:
          - secretRef:
              name: {{ include "common.names.fullname" . }}
{{- end }}
{{- end }}