apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "copy-database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "copy-database.labels" . | nindent 4 }}
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
            {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          labels:
            {{- include "copy-database.selectorLabels" . | nindent 12 }}
        spec:
            {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            - name: pull-secret
            {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                {{ include "copy-database.config.volumeMounts" . | indent 16 }}
              env:
                - name: SOURCE_DATABASE
                  value: {{ .Values.source.database }}
                - name: DESTINATION_DATABASE
                  value: {{ .Values.destination.database }}
          restartPolicy: OnFailure
          volumes:
            {{- include "copy-database.config.volumes" . | indent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
