apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "copy-database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "copy-database.labels" . | nindent 4 }}
spec:
  suspend: {{ .Values.suspendJob }}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      {{- include "copy-database.selectorLabels" . | nindent 6 }}*/}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "copy-database.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: pull-secret
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{ include "copy-database.config.volumeMounts" . | indent 12 }}
          env:
            - name: SOURCE_DATABASE
              value: {{ .Values.source.database }}
            - name: DESTINATION_DATABASE
              value: {{ .Values.destination.database }}
      restartPolicy: Never
      volumes:
        {{- include "copy-database.config.volumes" . | indent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
