apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pull-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://ghcr.io": {
          "auth": "{{ index .Values.imagePullSecrets.github | b64enc }}"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
