apiVersion: v2
name: php-stack
version: 3.0.0
appVersion: 0.0.0
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    import-values:
      - child: addons
        parent: addons
  - name: mariadb
    version: ^0.16
    repository: https://cloudpirates-io.github.io/helm-charts
    condition: mariadb.enabled
  - name: redis
    version: ^0.30
    repository: https://cloudpirates-io.github.io/helm-charts
    condition: redis.enabled
