apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
stringData:
  api-token: "{{ .Values.apiToken }}"
