apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}
  labels:
    {{- include "prometheus-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Name }}
  selector:
    matchLabels:
      {{- include "prometheus-exporter.selectorLabels" . | nindent 6 }}
