apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}-metrics
  labels:
    {{- include "prometheus-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP

  selector:
    {{- include "prometheus-exporter.selectorLabels" . | nindent 4 }}
