apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}-monitor
  labels:
    release: kps
    app: {{ include "prometheus-exporter.fullname" . }}
spec:
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    {{- include "prometheus-exporter.selectorLabels" . | nindent 4 }}
