apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matomo.fullname" . }}
  labels: {{- include "matomo.labels" . | nindent 4 }}
data:
  php.ini: |
    memory_limit={{ .Values.extraEnvs.PHP_MEMORY_LIMIT }}
    mysqlnd.net_read_timeout={{ .Values.extraEnvs.MYSQLND_NET_READ_TIMEOUT }}
  matomo.conf: |
    upstream php-handler {
      server localhost:9000;
    }

    server {
      listen 80;

      add_header Referrer-Policy origin; # make sure outgoing links don't show the URL to the Matomo instance
      root /var/www/html; # replace with path to your matomo instance
      index index.php;
      try_files $uri $uri/ =404;

      ## Rewrite matomo.js and matomo.php to reduce adblocking rate
      rewrite ^/mj /matomo.js last;
      rewrite ^/mp /matomo.php last;

      ## only allow accessing the following php files
      location ~ ^/(index|matomo|piwik|js/index|plugins/HeatmapSessionRecording/configs).php {
        # regex to split $uri to $fastcgi_script_name and $fastcgi_path
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # Check that the PHP script exists before passing it
        try_files $fastcgi_script_name =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTP_PROXY ""; # prohibit httpoxy: https://httpoxy.org/

        # GeoIP params
        # fastcgi_param MM_CONTINENT_CODE $http_x_geoip_continent_code;
        # fastcgi_param MM_CONTINENT_NAME $http_x_geoip_continent_name;

        fastcgi_param MM_COUNTRY_CODE $http_x_geoip_country_code;
        fastcgi_param MM_COUNTRY_NAME $http_x_geoip_country_name;

        fastcgi_param MM_REGION_CODE $http_x_geoip_region_code;
        fastcgi_param MM_REGION_NAME $http_x_geoip_region_name;

        fastcgi_param MM_POSTAL_CODE $http_x_geoip_postal_code;
        fastcgi_param MM_CITY_NAME $http_x_geoip_city;

        fastcgi_param MM_LATITUDE $http_x_geoip_latitude;
        fastcgi_param MM_LONGITUDE $http_x_geoip_longitude;

        fastcgi_param MM_ORG $http_x_geoip_org;


        fastcgi_pass php-handler;
      }

      ## deny access to all other .php files
      location ~* ^.+\.php$ {
        deny all;
        return 403;
      }

      ## disable all access to the following directories
      location ~ /(config|tmp|core|lang) {
        deny all;
        return 403; # replace with 404 to not show these directories exist
      }
      location ~ /\.ht {
        deny all;
        return 403;
      }

      location ~ js/container_.*_preview\.js$ {
        expires off;
        add_header Cache-Control 'private, no-cache, no-store';
      }

      location ~ \.(gif|ico|jpg|png|svg|js|css|htm|html|mp3|mp4|wav|ogg|avi|ttf|eot|woff|woff2|json)$ {
        allow all;
        ## Cache images,CSS,JS and webfonts for an hour
        ## Increasing the duration may improve the load-time, but may cause old files to show after an Matomo upgrade
        expires 1h;
        add_header Pragma public;
        add_header Cache-Control "public";
      }

      location ~ /(libs|vendor|plugins|misc/user) {
        deny all;
        return 403;
      }

      ## properly display textfiles in root directory
      location ~/(.*\.md|LEGALNOTICE|LICENSE) {
        default_type text/plain;
      }
    }
  {{ tpl (.Files.Glob "scripts/*").AsConfig . | nindent 2 }}

  {{- if .Values.misc.favicon }}
  favicon.png: |-{{ .Values.misc.favicon | nindent 4 }}
  {{- end }}

  {{- if .Values.misc.logo }}
  logo.png: |-{{ .Values.misc.logo | nindent 4 }}
  {{- end }}

  {{- if index .Values.misc "logo-header" }}
  logo-header.png: |-{{ index .Values.misc "logo-header" | nindent 4 }}
  {{- end }}
