{{- if .Values.cleanup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "matomo.fullname" . }}-cleanup
  labels: {{- include "matomo.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cleanup.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 31536000
      backoffLimit: 3
      template:
        spec:
          imagePullSecrets:
            - name: pull-secret
          restartPolicy: Never
          containers:
          - name: {{ include "matomo.name" . }}
            image: "{{ .Values.cleanup.image.repository }}:{{ .Values.cleanup.image.tag }}"
            imagePullPolicy: {{ .Values.cleanup.image.pullPolicy }}

            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi

            volumeMounts:
              - name: secret-config
                mountPath: /app/.env
                subPath: .env
          volumes:
            - name: secret-config
              secret:
                secretName: {{ include "matomo.fullname" . }}-cleanup-config
{{- end -}}
