{{- if .Values.cronjobs.archive.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "matomo.fullname" . }}-archive
  labels: {{- include "matomo.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjobs.archive.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjobs.archive.concurrencyPolicy | default "Allow" }}
{{- if .Values.cronjobs.archive.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cronjobs.archive.startingDeadlineSeconds }}
{{- end }}
  successfulJobsHistoryLimit: {{ .Values.cronjobs.archive.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .Values.cronjobs.archive.failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      {{- if .Values.cronjobs.archive.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.cronjobs.archive.activeDeadlineSeconds }}
      {{- end }}
      {{- if .Values.cronjobs.archive.parallelism }}
      parallelism: {{ .Values.cronjobs.archive.parallelism }}
      {{- end }}
      backoffLimit: {{ .Values.cronjobs.archive.backoffLimit | default 3 }}
      template:
        spec:
        {{- if .Values.image.pullSecrets }}
          imagePullSecrets:
          {{- range .Values.image.pullSecrets }}
            - name: {{ . }}
          {{- end }}
        {{- end }}
          # securityContext:
          #   fsGroup: 82
          restartPolicy: Never
          {{- include "matomo.custom.initContainers" . | nindent 10 }}
          containers:
          - name: {{ include "matomo.name" . }}
            # securityContext:
            #   runAsUser: 82
            #   runAsGroup: 82
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: MATOMO_DATABASE_HOST
                value: {{ include "matomo.databaseHost" . | quote }}
              - name: MATOMO_DATABASE_ADAPTER
                value: {{ .Values.database.adapter | quote }}
              - name: MATOMO_DATABASE_TABLES_PREFIX
                value: {{ .Values.database.tables_prefix | quote }}
              - name: MATOMO_DATABASE_DBNAME
                value: {{ .Values.database.dbname | quote }}
              - name: MATOMO_GENERAL_SALT
                value: {{ required "`.Values.salt` is not set." .Values.salt | quote }}
            {{- range $key, $value := .Values.extraEnvs }}
              - name: {{ $key }}
                value: {{ $value | quote }}
            {{- end }}
            envFrom:
              - secretRef:
                  name: {{ include "matomo.fullname" . }}-envs
            args: ['/bin/sh', '-c', '/usr/local/bin/php /var/www/html/console core:archive --url={{ include "matomo.fullname" . }}']
          {{- with .Values.cronjobs.archive.resources }}
            resources:
              {{ toYaml . | indent 14 | trim}}
          {{- end }}
            volumeMounts:
              - name: data
                mountPath: {{ .Values.persistence.mountPath }}
                subPath: {{ .Values.persistence.subPath }}
              {{- include "matomo.custom.volumeMounts" . | nindent 14 }}
              {{- include "matomo.config.volumeMounts" . | nindent 14 }}
          volumes:
            - name: data
            {{- if .Values.persistence.enabled }}
              persistentVolumeClaim:
                claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "matomo.fullname" . }}{{- end }}
            {{- else }}
              emptyDir: {}
            {{- end }}
            {{- include "matomo.config.volumes" . | nindent 12 }}
            {{- include "matomo.custom.volumes" . | nindent 12 }}
{{- end -}}
