kind: Secret
apiVersion: v1
metadata:
  name: {{ include "matomo.fullname" . }}-envs
  labels: {{- include "matomo.labels" . | nindent 4 }}
data:
  MATOMO_DATABASE_USERNAME: {{ .Values.database.username | b64enc | quote }}
  MATOMO_DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  {{- if .Values.license_key }}
  MATOMO_LICENSE_KEY: {{ .Values.license_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.geoip.maxmind_license_key }}
  MATOMO_MAXMIND_LICENSE: {{ .Values.geoip.maxmind_license_key | b64enc | quote }}
  {{- end }}
