kind: Secret
apiVersion: v1
metadata:
  name: {{ include "matomo.fullname" . }}-cleanup-config
  labels: {{- include "matomo.labels" . | nindent 4 }}
stringData:
  .env: |-
    DB_HOST={{ .Values.database.host | quote }}
    DB_USER={{ .Values.database.username | quote }}
    DB_PASS={{ .Values.database.password | quote }}
    DB_NAME={{ .Values.database.dbname | quote }}
    DB_PORT=3306
    DB_TABLE_PREFIX={{ .Values.database.tables_prefix | quote }}
