apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "matomo.fullname" . }}-queue-metrics
  labels: {{- include "matomo.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  endpoints:
    - port: http
      path: "/index.php?module=API&method=QueueMonitoring.getQueueMetrics&format=original"
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Name }}
  selector:
    matchLabels: {{- include "matomo.labels" . | nindent 6 }}
      app.kubernetes.io/component: app
