apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "demoshop.name" $ }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "demoshop.labels" $ | nindent 4 }}
spec:
  serviceName: {{ include "demoshop.name" $ }}-database
  replicas: 1
  selector:
    matchLabels:
        {{ include "demoshop.selectorLabels" $ | nindent 8 }}
  template:
    metadata:
      annotations:
        checksum/pull-secret: {{ include (print $.Template.BasePath "/image-pull-secret.yaml") $ | sha256sum }}
      labels:
        {{ include "demoshop.labels" $ | nindent 8 }}
        app.kubernetes.io/app: database
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        {{- if and .name .repo .auth }}
        - name: {{ include "demoshop.name" $ }}-{{ .name }}
        {{- end }}
        {{- end }}
      {{- if .Values.database.initialDumps }}
      initContainers:
      {{- range $key, $dump := .Values.database.initialDumps }}
      {{- if .url }}
        - name: database-dump-downloader-{{ $key }}
          image: alpine/curl:latest
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          args:
            - {{ $dump.url }}
            - -sSLO
            - --remote-header-name
            - --output-dir
            - /docker-entrypoint-initdb.d/
            {{- if $dump.auth }}
            - --user
            - {{ $dump.auth }}
            {{- end }}
            {{- if $dump.userAgent }}
            - --user-agent
            - {{ $dump.userAgent }}
            {{- end }}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: {{ include "demoshop.name" $ }}-db-init
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
        - name: database
          {{- with .Values.database.image }}
          image: "{{ .name }}:{{ .tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.database.rootPassword | quote }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.database.name | quote }}"
            - name: MYSQL_USER
              value: "{{ .Values.database.user | quote }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.database.password | quote }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: {{ include "demoshop.name" $ }}-database-storage
              mountPath: /var/lib/mysql
        {{- if .Values.database.initialDumps }}
            - mountPath: /docker-entrypoint-initdb.d
              name: {{ include "demoshop.name" $ }}-db-init
        {{- end }}
      {{- if .Values.database.initialDumps }}
      volumes:
        - name: {{ include "demoshop.name" $ }}-db-init
          emptyDir: {}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "demoshop.name" $ }}-database-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "{{ .Values.database.storageSize }}"
---
