{{- range .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "demoshop.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ (printf "{\"auths\":{\"https://ghcr.io\":{\"auth\":\"%s\"}}}" .secret) | b64enc | quote }}
---
{{- end }}
