{{- range $pullSecret := .Values.imagePullSecrets }}
  {{- if and $pullSecret.name $pullSecret.repo $pullSecret.auth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pullSecret.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "demoshop.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ $pullSecret.repo }}": {
          "auth": "{{ $pullSecret.auth }}"
        }
      }
    }
---
  {{- end -}}
{{- end -}}
