apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "demoshop.name" $ }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "demoshop.labels" $ | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - "{{ .Values.domain }}"
  rules:
    - host: "{{ .Values.domain }}"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "demoshop.name" $ }}-shop
              port:
                number: 80
