{{- if and (.Values.shop.sharedAssets.enabled) (.Values.shop.sharedAssets.storageClass) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "demoshop.name" . }}-assets-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.shop.sharedAssets.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.shop.sharedAssets.storageSize }}"
---
{{- end }}
