apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demoshop.name" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{ include "demoshop.labels" $ | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{ include "demoshop.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/pull-secret: {{ include (print $.Template.BasePath "/image-pull-secret.yaml") $ | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/shop-configmap.yaml") $ | sha256sum }}
      labels:
        {{ include "demoshop.labels" $ | nindent 8 }}
        app.kubernetes.io/app: shop
    spec:
      imagePullSecrets:
        {{- range $pullSecret := $.Values.imagePullSecrets }}
        {{- if and $pullSecret.name $pullSecret.repo $pullSecret.auth }}
        - name: {{ include "demoshop.name" $ }}-{{ $pullSecret.name }}
        {{- end }}
        {{- end }}
      initContainers:
        - name: metakube-init
          image: busybox
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          command: [sh, -c]
          args:
            - |
              echo "10" > /proc/sys/net/ipv4/tcp_keepalive_intvl
              echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes
              echo "10" > /proc/sys/net/ipv4/tcp_keepalive_time
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
        - name: init-unix-domain-socket
          image: busybox
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          command: [sh, -c]
          args:
              - chown -R 33:33 /sockets
          volumeMounts:
            - name: sockets
              mountPath: /sockets
        {{- if and $.Values.shop.sharedAssets.enabled $.Values.shop.sharedAssets.storageClass }}
        - name: copy-shared-assets
          {{- with $.Values.shop.image }}
          image: "{{ .name }}:{{ .tag }}"
          {{- end }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          command: [ "sh", "-c", "rsync -auL /assets/* /shared-assets; chown -R 33:33 /shared-assets" ]
          volumeMounts:
            - name: shared-assets
              mountPath: /shared-assets
        {{- end }}
        {{- range $.Values.shop.persistence }}
        {{- if .storageClass }}
        - name: copy-{{ .name }}
          {{- with $.Values.shop.image }}
          image: "{{ .name }}:{{ .tag }}"
          {{- end }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          command: [ "sh", "-c", "rsync -auL {{ .path }}/* /copy/{{ .name }}; chown -R 33:33 /copy/{{ .name }}" ]
          volumeMounts:
            - name: {{ .name }}
              mountPath: /copy/{{ .name }}
        {{- end }}
        {{- end }}
        {{- range $.Values.shop.initCommands }}
        {{- if and .name .command }}
        - name: {{ .name }}
          {{- with $.Values.shop.image }}
          image: "{{ .name }}:{{ .tag }}"
          {{- end }}
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          env:
            {{- range $name, $value := $.Values.shop.envVars }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if and .user (ne .user "root") }}
          command: ["su", "-s", "/bin/sh", "{{ .user }}", "-c"]
          {{- else }}
          command: ["/bin/sh", "-c"]
          {{- end }}
          args:
            - {{ .command }}
        {{- if and $.Values.shop.sharedAssets.enabled $.Values.shop.sharedAssets.storageClass }}
          volumeMounts:
            - name: shared-assets
              mountPath: /assets
        {{- end }}
        {{- end }}
        {{- end }}

      containers:
      - name: shop
        {{- with $.Values.shop.image }}
        image: "{{ .name }}:{{ .tag }}"
        {{- end }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        ports:
        - containerPort: 9000
        env:
          {{- range $name, $value := $.Values.shop.envVars }}
          - name: {{ $name }}
            value: {{ $value | quote }}
          {{- end }}
        volumeMounts:
          - name: sockets
            mountPath: /sockets
          {{- if and ($.Values.shop.sharedAssets.enabled) ($.Values.shop.sharedAssets.storageClass) }}
          - name: shared-assets
            mountPath: /assets
          {{- end }}
          {{- range $.Values.shop.persistence }}
          {{- if .storageClass }}
          - name: {{ .name }}
            mountPath: {{ .path }}
          {{- end }}
          {{- end }}
        {{- with $.Values.shop.postStartCommand }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", {{ . | quote }}]
        {{- end }}

      - name: nginx
        {{- with $.Values.nginx.image }}
        image: "{{ .name }}:{{ .tag }}"
        {{- end }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
          - name: sockets
            mountPath: /sockets
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          {{- if and ($.Values.shop.sharedAssets.enabled) ($.Values.shop.sharedAssets.storageClass) }}
          - name: shared-assets
            mountPath: /var/www
          {{- end }}

      volumes:
        - name: sockets
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: {{ include "demoshop.name" $ }}-nginx-config
        {{- if and ($.Values.shop.sharedAssets.enabled) ($.Values.shop.sharedAssets.storageClass) }}
        - name: shared-assets
          persistentVolumeClaim:
            claimName: {{ include "demoshop.name" $ }}-assets-pvc
        {{- end }}
        {{- range $.Values.shop.persistence }}
        {{- if .storageClass }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "demoshop.name" $ }}-{{ .name }}
        {{- end }}
        {{- end }}
---
