apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demoshop.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "demoshop.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "demoshop.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "demoshop.labels" $ | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      initContainers:
      - name: metakube-init
        image: busybox
        command: [sh, -c]
        args:
          - |
            echo "10" > /proc/sys/net/ipv4/tcp_keepalive_intvl
            echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes
            echo "10" > /proc/sys/net/ipv4/tcp_keepalive_time
      {{ if and .Values.shop.sharedAssets.enabled .Values.shop.sharedAssets.storageClass }}
      - name: copy-shared-assets
        image: "{{ .Values.shop.image }}"
        command: [ "sh", "-c", "rsync -auL /assets/* /shared-assets"]
        volumeMounts:
          - name: shared-assets
            mountPath: /shared-assets
      {{- end }}

      containers:
      - name: php-fpm
        image: "{{ .Values.shop.image }}"
        ports:
        - containerPort: 9000
        env:
          {{- range $name, $value := .Values.shop.envVars }}
          - name: {{ $name }}
            value: {{ $value }}
          {{- end }}
        volumeMounts:
        {{- if and (.Values.shop.sharedAssets.enabled) (.Values.shop.sharedAssets.storageClass) }}
        - name: generated-assets
          mountPath: /assets
        {{- end }}

      - name: nginx
        image: "{{ .Values.nginx.image }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        {{- if and (.Values.shop.sharedAssets.enabled) (.Values.shop.sharedAssets.storageClass) }}
        - name: shared-assets
          mountPath: /var/www
        {{- end }}

      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "demoshop.name" . }}-nginx-config
        {{- if and (.Values.shop.sharedAssets.enabled) (.Values.shop.sharedAssets.storageClass) }}
        - name: shared-assets
          persistentVolumeClaim:
            claimName: {{ include "demoshop.name" . }}-assets-pvc
        {{- end }}
