apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demoshop.name" $ }}-nginx-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "demoshop.labels" $ | nindent 4 }}
data:
  default.conf: |-
    server {
        server_tokens off;
        listen 80;
        server_name _;
        root /var/www;
        index index.php index.html;

        location /healthz {
            return 200 "OK";
        }

        {{ .Values.nginx.locations | nindent 8 }}
    }
---
