domain: "shop.k8s.makaira.io"

imagePullSecrets:
  - name: ""
    repo: ""
    auth: ""

shop:
  image:
    name: php
    tag: 8.4-fpm
  sharedAssets:
    enabled: false
    storageClass: ""
    storageSize: "5Gi"
  envVars:

nginx:
  image:
    name: nginx
    tag: stable
  locations: |-
    location / {
      gzip_static on;
      try_files $uri @php;
    }

    location @php {
      include fastcgi_params;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME /app/public/$fastcgi_script_name;
    }

database:
  image:
    name: mysql
    tag: 8.0
  name: "database"
  user: "username"
  password: "password"
  rootPassword: "SetYourOwnRootPassword!"
  storageSize: "5Gi"
