name: Release a new version
on:
  push:
    branches:
      - stable

jobs:
  release:
    name: Release
    if: |
      !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]')) &&
      !(github.event_name == 'pull_request' && contains(join(github.event.pull_request.title, github.event.pull_request.body), '[skip ci]'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Semantic release
        run: ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          GIT_AUTHOR_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}

      - name: Update index.yaml
        run: ./cr.sh
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_OWNER: MakairaIO
          CR_GIT_REPO: helm-charts
          CR_PACKAGE_PATH: charts
          CR_INDEX_PATH: index.yaml
          CR_PAGES_BRANCH: gh-pages
          CR_COMMIT_MESSAGE: "chore: update index.yaml"
          CR_RELEASE_NAME_TEMPLATE: "{{ .Name }}-v{{ .Version }}"

      - name: Trigger Renovate
        uses: AlexanderBabel/action-renovate-checkbox@v1
        with:
          master-issue-id: 16
          repo: kubernetes-config
          token: ${{ secrets.GH_TOKEN }}
